name: my second workflow

on:
  push:
    branches: [ master, dev, devvy ]
  pull_request:
    branches: [ master, dev, devvy ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line scrips
      run: |
        echo Add another action to build,
        echo test, and depley your project
