name: Build and tester
on:
  push:
    branches: [ master, dev, devvy ]
  pull_request:
    branches: [ master, dev, devvy ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dotnet SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.x'

    - name: Try building my code
      run: dotnet build

    - name: Run unit tests on my code
      run: dotnet test -v n
