name: my first workflow

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, worlds!

    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy to your project.

